[package]
name = "term-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
cssparser = "0.33.0"
minidom = "0.15.2"
use = "0.0.1-pre.0"
xml = "0.8.10"
